# Generated by Django 5.2 on 2025-05-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_score_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('question',)},
        ),
    ]
