# version: "3.9"

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    container_name: postgres_hackatom
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_dump.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment: 
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

volumes:
  postgres_data:
