FROM python:3.11-slim

WORKDIR /app

COPY backend /app/

COPY db_dump.sql /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
